### ISSUE TITLE
Implement frequency database building for sequence variants

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/mehari#2]
We need to annotate frequencies from frequency databases. We need to store them in fast key/value access mode. We should use rocksdb for such databases.

- [ ] implement a CLI for importing the databases

GRCh37 & GRCh38

- [ ] gnomAD exomes
- [ ] gnomAD genomes
- [ ] gnomAD mtDB
- [ ] helixmtdb

The following are considered outdated by now (2023/03/03)

- mtdb
- mitomap
- IGSR
    - GRCh38 http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20190312_biallelic_SNV_and_INDEL/
    - GRCh37 http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/

GRCh37 only

- ExAC

**Comment by xiamaz** [comment]
Might be interesting: https://github.com/brentp/echtvar

**Comment by holtgrewe** [comment]
> Might be interesting: https://github.com/brentp/echtvar

Filtering will remain in VarFish for now ;-)
